/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guidesSidebar: [
    'introduction',
    'quickstart',
    {
      type: 'category',
      label: 'Overview',
      collapsed: true,
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'overview',
        },
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        },
      ],
    },
  ],
  examplesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'examples',
    },
  ],
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};

module.exports = sidebars;
