export default [
  { Entity: 'Abkhazia', Code: 'OWID_ABK', Year: 2015, Continent: 'Asia' },
  { Entity: 'Afghanistan', Code: 'AFG', Year: 2015, Continent: 'Asia' },
  { Entity: 'Akrotiri and Dhekelia', Code: 'OWID_AKD', Year: 2015, Continent: 'Asia' },
  { Entity: 'Albania', Code: 'ALB', Year: 2015, Continent: 'Europe' },
  { Entity: 'Algeria', Code: 'DZA', Year: 2015, Continent: 'Africa' },
  { Entity: 'American Samoa', Code: 'ASM', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Andorra', Code: 'AND', Year: 2015, Continent: 'Europe' },
  { Entity: 'Angola', Code: 'AGO', Year: 2015, Continent: 'Africa' },
  { Entity: 'Anguilla', Code: 'AIA', Year: 2015, Continent: 'North America' },
  { Entity: 'Antarctica', Code: 'ATA', Year: 2015, Continent: 'Antarctica' },
  { Entity: 'Antigua and Barbuda', Code: 'ATG', Year: 2015, Continent: 'North America' },
  { Entity: 'Argentina', Code: 'ARG', Year: 2015, Continent: 'South America' },
  { Entity: 'Armenia', Code: 'ARM', Year: 2015, Continent: 'Asia' },
  { Entity: 'Aruba', Code: 'ABW', Year: 2015, Continent: 'North America' },
  { Entity: 'Australia', Code: 'AUS', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Austria', Code: 'AUT', Year: 2015, Continent: 'Europe' },
  { Entity: 'Austria-Hungary', Code: 'OWID_AUH', Year: 2015, Continent: 'Europe' },
  { Entity: 'Azerbaijan', Code: 'AZE', Year: 2015, Continent: 'Asia' },
  { Entity: 'Baden', Code: 'OWID_BAD', Year: 2015, Continent: 'Europe' },
  { Entity: 'Bahamas', Code: 'BHS', Year: 2015, Continent: 'North America' },
  { Entity: 'Bahrain', Code: 'BHR', Year: 2015, Continent: 'Asia' },
  { Entity: 'Bangladesh', Code: 'BGD', Year: 2015, Continent: 'Asia' },
  { Entity: 'Barbados', Code: 'BRB', Year: 2015, Continent: 'North America' },
  { Entity: 'Bavaria', Code: 'OWID_BAV', Year: 2015, Continent: 'Europe' },
  { Entity: 'Belarus', Code: 'BLR', Year: 2015, Continent: 'Europe' },
  { Entity: 'Belgium', Code: 'BEL', Year: 2015, Continent: 'Europe' },
  { Entity: 'Belize', Code: 'BLZ', Year: 2015, Continent: 'North America' },
  { Entity: 'Benin', Code: 'BEN', Year: 2015, Continent: 'Africa' },
  { Entity: 'Bermuda', Code: 'BMU', Year: 2015, Continent: 'North America' },
  { Entity: 'Bhutan', Code: 'BTN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Bolivia', Code: 'BOL', Year: 2015, Continent: 'South America' },
  {
    Entity: 'Bonaire Sint Eustatius and Saba',
    Code: 'BES',
    Year: 2015,
    Continent: 'North America',
  },
  { Entity: 'Bosnia and Herzegovina', Code: 'BIH', Year: 2015, Continent: 'Europe' },
  { Entity: 'Botswana', Code: 'BWA', Year: 2015, Continent: 'Africa' },
  { Entity: 'Bouvet Island', Code: 'BVT', Year: 2015, Continent: 'Antarctica' },
  { Entity: 'Brazil', Code: 'BRA', Year: 2015, Continent: 'South America' },
  { Entity: 'British Indian Ocean Territory', Code: 'IOT', Year: 2015, Continent: 'Asia' },
  { Entity: 'British Virgin Islands', Code: 'VGB', Year: 2015, Continent: 'North America' },
  { Entity: 'Brunei', Code: 'BRN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Bulgaria', Code: 'BGR', Year: 2015, Continent: 'Europe' },
  { Entity: 'Burkina Faso', Code: 'BFA', Year: 2015, Continent: 'Africa' },
  { Entity: 'Burundi', Code: 'BDI', Year: 2015, Continent: 'Africa' },
  { Entity: 'Cambodia', Code: 'KHM', Year: 2015, Continent: 'Asia' },
  { Entity: 'Cameroon', Code: 'CMR', Year: 2015, Continent: 'Africa' },
  { Entity: 'Canada', Code: 'CAN', Year: 2015, Continent: 'North America' },
  { Entity: 'Cape Verde', Code: 'CPV', Year: 2015, Continent: 'Africa' },
  { Entity: 'Cayman Islands', Code: 'CYM', Year: 2015, Continent: 'North America' },
  { Entity: 'Central African Republic', Code: 'CAF', Year: 2015, Continent: 'Africa' },
  { Entity: 'Chad', Code: 'TCD', Year: 2015, Continent: 'Africa' },
  { Entity: 'Channel Islands', Code: 'OWID_CIS', Year: 2015, Continent: 'Europe' },
  { Entity: 'Chile', Code: 'CHL', Year: 2015, Continent: 'South America' },
  { Entity: 'China', Code: 'CHN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Christmas Island', Code: 'CXR', Year: 2015, Continent: 'Asia' },
  { Entity: 'Cocos Islands', Code: 'CCK', Year: 2015, Continent: 'Asia' },
  { Entity: 'Colombia', Code: 'COL', Year: 2015, Continent: 'South America' },
  { Entity: 'Comoros', Code: 'COM', Year: 2015, Continent: 'Africa' },
  { Entity: 'Congo', Code: 'COG', Year: 2015, Continent: 'Africa' },
  { Entity: 'Cook Islands', Code: 'COK', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Costa Rica', Code: 'CRI', Year: 2015, Continent: 'North America' },
  { Entity: "Cote d'Ivoire", Code: 'CIV', Year: 2015, Continent: 'Africa' },
  { Entity: 'Croatia', Code: 'HRV', Year: 2015, Continent: 'Europe' },
  { Entity: 'Cuba', Code: 'CUB', Year: 2015, Continent: 'North America' },
  { Entity: 'Curacao', Code: 'CUW', Year: 2015, Continent: 'North America' },
  { Entity: 'Cyprus', Code: 'CYP', Year: 2015, Continent: 'Europe' },
  { Entity: 'Czechia', Code: 'CZE', Year: 2015, Continent: 'Europe' },
  { Entity: 'Czechoslovakia', Code: 'OWID_CZS', Year: 2015, Continent: 'Europe' },
  { Entity: 'Democratic Republic of Congo', Code: 'COD', Year: 2015, Continent: 'Africa' },
  { Entity: 'Denmark', Code: 'DNK', Year: 2015, Continent: 'Europe' },
  { Entity: 'Djibouti', Code: 'DJI', Year: 2015, Continent: 'Africa' },
  { Entity: 'Dominica', Code: 'DMA', Year: 2015, Continent: 'North America' },
  { Entity: 'Dominican Republic', Code: 'DOM', Year: 2015, Continent: 'North America' },
  { Entity: 'East Germany', Code: 'OWID_GDR', Year: 2015, Continent: 'Europe' },
  { Entity: 'Ecuador', Code: 'ECU', Year: 2015, Continent: 'South America' },
  { Entity: 'Egypt', Code: 'EGY', Year: 2015, Continent: 'Africa' },
  { Entity: 'El Salvador', Code: 'SLV', Year: 2015, Continent: 'North America' },
  { Entity: 'Equatorial Guinea', Code: 'GNQ', Year: 2015, Continent: 'Africa' },
  { Entity: 'Eritrea', Code: 'ERI', Year: 2015, Continent: 'Africa' },
  { Entity: 'Eritrea and Ethiopia', Code: 'OWID_ERE', Year: 2015, Continent: 'Africa' },
  { Entity: 'Estonia', Code: 'EST', Year: 2015, Continent: 'Europe' },
  { Entity: 'Eswatini', Code: 'SWZ', Year: 2015, Continent: 'Africa' },
  { Entity: 'Ethiopia', Code: 'ETH', Year: 2015, Continent: 'Africa' },
  { Entity: 'Faeroe Islands', Code: 'FRO', Year: 2015, Continent: 'Europe' },
  { Entity: 'Falkland Islands', Code: 'FLK', Year: 2015, Continent: 'South America' },
  { Entity: 'Fiji', Code: 'FJI', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Finland', Code: 'FIN', Year: 2015, Continent: 'Europe' },
  { Entity: 'France', Code: 'FRA', Year: 2015, Continent: 'Europe' },
  { Entity: 'French Guiana', Code: 'GUF', Year: 2015, Continent: 'South America' },
  { Entity: 'French Polynesia', Code: 'PYF', Year: 2015, Continent: 'Oceania' },
  {
    Entity: 'French Southern Territories',
    Code: 'ATF',
    Year: 2015,
    Continent: 'Antarctica',
  },
  { Entity: 'Gabon', Code: 'GAB', Year: 2015, Continent: 'Africa' },
  { Entity: 'Gambia', Code: 'GMB', Year: 2015, Continent: 'Africa' },
  { Entity: 'Georgia', Code: 'GEO', Year: 2015, Continent: 'Asia' },
  { Entity: 'Germany', Code: 'DEU', Year: 2015, Continent: 'Europe' },
  { Entity: 'Ghana', Code: 'GHA', Year: 2015, Continent: 'Africa' },
  { Entity: 'Gibraltar', Code: 'GIB', Year: 2015, Continent: 'Europe' },
  { Entity: 'Greece', Code: 'GRC', Year: 2015, Continent: 'Europe' },
  { Entity: 'Greenland', Code: 'GRL', Year: 2015, Continent: 'North America' },
  { Entity: 'Grenada', Code: 'GRD', Year: 2015, Continent: 'North America' },
  { Entity: 'Guadeloupe', Code: 'GLP', Year: 2015, Continent: 'North America' },
  { Entity: 'Guam', Code: 'GUM', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Guatemala', Code: 'GTM', Year: 2015, Continent: 'North America' },
  { Entity: 'Guernsey', Code: 'GGY', Year: 2015, Continent: 'Europe' },
  { Entity: 'Guinea', Code: 'GIN', Year: 2015, Continent: 'Africa' },
  { Entity: 'Guinea-Bissau', Code: 'GNB', Year: 2015, Continent: 'Africa' },
  { Entity: 'Guyana', Code: 'GUY', Year: 2015, Continent: 'South America' },
  { Entity: 'Haiti', Code: 'HTI', Year: 2015, Continent: 'North America' },
  { Entity: 'Hanover', Code: 'OWID_HAN', Year: 2015, Continent: 'Europe' },
  {
    Entity: 'Heard Island and McDonald Islands',
    Code: 'HMD',
    Year: 2015,
    Continent: 'Antarctica',
  },
  { Entity: 'Hesse Electoral', Code: 'OWID_HSE', Year: 2015, Continent: 'Europe' },
  { Entity: 'Hesse Grand Ducal', Code: 'OWID_HSG', Year: 2015, Continent: 'Europe' },
  { Entity: 'Honduras', Code: 'HND', Year: 2015, Continent: 'North America' },
  { Entity: 'Hong Kong', Code: 'HKG', Year: 2015, Continent: 'Asia' },
  { Entity: 'Hungary', Code: 'HUN', Year: 2015, Continent: 'Europe' },
  { Entity: 'Iceland', Code: 'ISL', Year: 2015, Continent: 'Europe' },
  { Entity: 'India', Code: 'IND', Year: 2015, Continent: 'Asia' },
  { Entity: 'Indonesia', Code: 'IDN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Iran', Code: 'IRN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Iraq', Code: 'IRQ', Year: 2015, Continent: 'Asia' },
  { Entity: 'Ireland', Code: 'IRL', Year: 2015, Continent: 'Europe' },
  { Entity: 'Isle of Man', Code: 'IMN', Year: 2015, Continent: 'Europe' },
  { Entity: 'Israel', Code: 'ISR', Year: 2015, Continent: 'Asia' },
  { Entity: 'Italy', Code: 'ITA', Year: 2015, Continent: 'Europe' },
  { Entity: 'Jamaica', Code: 'JAM', Year: 2015, Continent: 'North America' },
  { Entity: 'Japan', Code: 'JPN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Jersey', Code: 'JEY', Year: 2015, Continent: 'Europe' },
  { Entity: 'Jordan', Code: 'JOR', Year: 2015, Continent: 'Asia' },
  { Entity: 'Kazakhstan', Code: 'KAZ', Year: 2015, Continent: 'Asia' },
  { Entity: 'Kenya', Code: 'KEN', Year: 2015, Continent: 'Africa' },
  { Entity: 'Kiribati', Code: 'KIR', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Kosovo', Code: 'OWID_KOS', Year: 2015, Continent: 'Europe' },
  { Entity: 'Kuwait', Code: 'KWT', Year: 2015, Continent: 'Asia' },
  { Entity: 'Kyrgyzstan', Code: 'KGZ', Year: 2015, Continent: 'Asia' },
  { Entity: 'Laos', Code: 'LAO', Year: 2015, Continent: 'Asia' },
  { Entity: 'Latvia', Code: 'LVA', Year: 2015, Continent: 'Europe' },
  { Entity: 'Lebanon', Code: 'LBN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Lesotho', Code: 'LSO', Year: 2015, Continent: 'Africa' },
  { Entity: 'Liberia', Code: 'LBR', Year: 2015, Continent: 'Africa' },
  { Entity: 'Libya', Code: 'LBY', Year: 2015, Continent: 'Africa' },
  { Entity: 'Liechtenstein', Code: 'LIE', Year: 2015, Continent: 'Europe' },
  { Entity: 'Lithuania', Code: 'LTU', Year: 2015, Continent: 'Europe' },
  { Entity: 'Luxembourg', Code: 'LUX', Year: 2015, Continent: 'Europe' },
  { Entity: 'Macao', Code: 'MAC', Year: 2015, Continent: 'Asia' },
  { Entity: 'Madagascar', Code: 'MDG', Year: 2015, Continent: 'Africa' },
  { Entity: 'Malawi', Code: 'MWI', Year: 2015, Continent: 'Africa' },
  { Entity: 'Malaysia', Code: 'MYS', Year: 2015, Continent: 'Asia' },
  { Entity: 'Maldives', Code: 'MDV', Year: 2015, Continent: 'Asia' },
  { Entity: 'Mali', Code: 'MLI', Year: 2015, Continent: 'Africa' },
  { Entity: 'Malta', Code: 'MLT', Year: 2015, Continent: 'Europe' },
  { Entity: 'Marshall Islands', Code: 'MHL', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Martinique', Code: 'MTQ', Year: 2015, Continent: 'North America' },
  { Entity: 'Mauritania', Code: 'MRT', Year: 2015, Continent: 'Africa' },
  { Entity: 'Mauritius', Code: 'MUS', Year: 2015, Continent: 'Africa' },
  { Entity: 'Mayotte', Code: 'MYT', Year: 2015, Continent: 'Africa' },
  { Entity: 'Mecklenburg Schwerin', Code: 'OWID_MEC', Year: 2015, Continent: 'Europe' },
  { Entity: 'Mexico', Code: 'MEX', Year: 2015, Continent: 'North America' },
  { Entity: 'Micronesia (country)', Code: 'FSM', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Modena', Code: 'OWID_MOD', Year: 2015, Continent: 'Europe' },
  { Entity: 'Moldova', Code: 'MDA', Year: 2015, Continent: 'Europe' },
  { Entity: 'Monaco', Code: 'MCO', Year: 2015, Continent: 'Europe' },
  { Entity: 'Mongolia', Code: 'MNG', Year: 2015, Continent: 'Asia' },
  { Entity: 'Montenegro', Code: 'MNE', Year: 2015, Continent: 'Europe' },
  { Entity: 'Montserrat', Code: 'MSR', Year: 2015, Continent: 'North America' },
  { Entity: 'Morocco', Code: 'MAR', Year: 2015, Continent: 'Africa' },
  { Entity: 'Mozambique', Code: 'MOZ', Year: 2015, Continent: 'Africa' },
  { Entity: 'Myanmar', Code: 'MMR', Year: 2015, Continent: 'Asia' },
  { Entity: 'Nagorno-Karabakh', Code: 'OWID_NAG', Year: 2015, Continent: 'Asia' },
  { Entity: 'Namibia', Code: 'NAM', Year: 2015, Continent: 'Africa' },
  { Entity: 'Nauru', Code: 'NRU', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Nepal', Code: 'NPL', Year: 2015, Continent: 'Asia' },
  { Entity: 'Netherlands', Code: 'NLD', Year: 2015, Continent: 'Europe' },
  { Entity: 'Netherlands Antilles', Code: 'ANT', Year: 2015, Continent: 'North America' },
  { Entity: 'New Caledonia', Code: 'NCL', Year: 2015, Continent: 'Oceania' },
  { Entity: 'New Zealand', Code: 'NZL', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Nicaragua', Code: 'NIC', Year: 2015, Continent: 'North America' },
  { Entity: 'Niger', Code: 'NER', Year: 2015, Continent: 'Africa' },
  { Entity: 'Nigeria', Code: 'NGA', Year: 2015, Continent: 'Africa' },
  { Entity: 'Niue', Code: 'NIU', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Norfolk Island', Code: 'NFK', Year: 2015, Continent: 'Oceania' },
  { Entity: 'North Korea', Code: 'PRK', Year: 2015, Continent: 'Asia' },
  { Entity: 'North Macedonia', Code: 'MKD', Year: 2015, Continent: 'Europe' },
  { Entity: 'Northern Cyprus', Code: 'OWID_CYN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Northern Mariana Islands', Code: 'MNP', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Norway', Code: 'NOR', Year: 2015, Continent: 'Europe' },
  { Entity: 'Oman', Code: 'OMN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Pakistan', Code: 'PAK', Year: 2015, Continent: 'Asia' },
  { Entity: 'Palau', Code: 'PLW', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Palestine', Code: 'PSE', Year: 2015, Continent: 'Asia' },
  { Entity: 'Panama', Code: 'PAN', Year: 2015, Continent: 'North America' },
  { Entity: 'Papua New Guinea', Code: 'PNG', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Paraguay', Code: 'PRY', Year: 2015, Continent: 'South America' },
  { Entity: 'Parma', Code: 'OWID_PMA', Year: 2015, Continent: 'Europe' },
  { Entity: 'Peru', Code: 'PER', Year: 2015, Continent: 'South America' },
  { Entity: 'Philippines', Code: 'PHL', Year: 2015, Continent: 'Asia' },
  { Entity: 'Pitcairn', Code: 'PCN', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Poland', Code: 'POL', Year: 2015, Continent: 'Europe' },
  { Entity: 'Portugal', Code: 'PRT', Year: 2015, Continent: 'Europe' },
  { Entity: 'Puerto Rico', Code: 'PRI', Year: 2015, Continent: 'North America' },
  { Entity: 'Qatar', Code: 'QAT', Year: 2015, Continent: 'Asia' },
  { Entity: 'Republic of Vietnam', Code: 'OWID_RVN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Reunion', Code: 'REU', Year: 2015, Continent: 'Africa' },
  { Entity: 'Romania', Code: 'ROU', Year: 2015, Continent: 'Europe' },
  { Entity: 'Russia', Code: 'RUS', Year: 2015, Continent: 'Europe' },
  { Entity: 'Rwanda', Code: 'RWA', Year: 2015, Continent: 'Africa' },
  { Entity: 'Saint Barthélemy', Code: 'BLM', Year: 2015, Continent: 'North America' },
  { Entity: 'Saint Helena', Code: 'SHN', Year: 2015, Continent: 'Africa' },
  { Entity: 'Saint Kitts and Nevis', Code: 'KNA', Year: 2015, Continent: 'North America' },
  { Entity: 'Saint Lucia', Code: 'LCA', Year: 2015, Continent: 'North America' },
  {
    Entity: 'Saint Martin (French part)',
    Code: 'MAF',
    Year: 2015,
    Continent: 'North America',
  },
  {
    Entity: 'Saint Pierre and Miquelon',
    Code: 'SPM',
    Year: 2015,
    Continent: 'North America',
  },
  {
    Entity: 'Saint Vincent and the Grenadines',
    Code: 'VCT',
    Year: 2015,
    Continent: 'North America',
  },
  { Entity: 'Samoa', Code: 'WSM', Year: 2015, Continent: 'Oceania' },
  { Entity: 'San Marino', Code: 'SMR', Year: 2015, Continent: 'Europe' },
  { Entity: 'Sao Tome and Principe', Code: 'STP', Year: 2015, Continent: 'Africa' },
  { Entity: 'Saudi Arabia', Code: 'SAU', Year: 2015, Continent: 'Asia' },
  { Entity: 'Saxony', Code: 'OWID_SAX', Year: 2015, Continent: 'Europe' },
  { Entity: 'Senegal', Code: 'SEN', Year: 2015, Continent: 'Africa' },
  { Entity: 'Serbia', Code: 'SRB', Year: 2015, Continent: 'Europe' },
  { Entity: 'Serbia and Montenegro', Code: 'OWID_SRM', Year: 2015, Continent: 'Europe' },
  { Entity: 'Serbia excluding Kosovo', Code: 'OWID_SEK', Year: 2015, Continent: 'Europe' },
  { Entity: 'Seychelles', Code: 'SYC', Year: 2015, Continent: 'Africa' },
  { Entity: 'Sierra Leone', Code: 'SLE', Year: 2015, Continent: 'Africa' },
  { Entity: 'Singapore', Code: 'SGP', Year: 2015, Continent: 'Asia' },
  {
    Entity: 'Sint Maarten (Dutch part)',
    Code: 'SXM',
    Year: 2015,
    Continent: 'North America',
  },
  { Entity: 'Slovakia', Code: 'SVK', Year: 2015, Continent: 'Europe' },
  { Entity: 'Slovenia', Code: 'SVN', Year: 2015, Continent: 'Europe' },
  { Entity: 'Solomon Islands', Code: 'SLB', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Somalia', Code: 'SOM', Year: 2015, Continent: 'Africa' },
  { Entity: 'Somaliland', Code: 'OWID_SML', Year: 2015, Continent: 'Africa' },
  { Entity: 'South Africa', Code: 'ZAF', Year: 2015, Continent: 'Africa' },
  {
    Entity: 'South Georgia and the South Sandwich Islands',
    Code: 'SGS',
    Year: 2015,
    Continent: 'South America',
  },
  { Entity: 'South Korea', Code: 'KOR', Year: 2015, Continent: 'Asia' },
  { Entity: 'South Ossetia', Code: 'OWID_SOS', Year: 2015, Continent: 'Asia' },
  { Entity: 'South Sudan', Code: 'SSD', Year: 2015, Continent: 'Africa' },
  { Entity: 'Spain', Code: 'ESP', Year: 2015, Continent: 'Europe' },
  { Entity: 'Sri Lanka', Code: 'LKA', Year: 2015, Continent: 'Asia' },
  { Entity: 'Sudan', Code: 'SDN', Year: 2015, Continent: 'Africa' },
  { Entity: 'Suriname', Code: 'SUR', Year: 2015, Continent: 'South America' },
  { Entity: 'Svalbard and Jan Mayen', Code: 'SJM', Year: 2015, Continent: 'Europe' },
  { Entity: 'Sweden', Code: 'SWE', Year: 2015, Continent: 'Europe' },
  { Entity: 'Switzerland', Code: 'CHE', Year: 2015, Continent: 'Europe' },
  { Entity: 'Syria', Code: 'SYR', Year: 2015, Continent: 'Asia' },
  { Entity: 'Taiwan', Code: 'TWN', Year: 2015, Continent: 'Asia' },
  { Entity: 'Tajikistan', Code: 'TJK', Year: 2015, Continent: 'Asia' },
  { Entity: 'Tanzania', Code: 'TZA', Year: 2015, Continent: 'Africa' },
  { Entity: 'Thailand', Code: 'THA', Year: 2015, Continent: 'Asia' },
  { Entity: 'Timor', Code: 'TLS', Year: 2015, Continent: 'Asia' },
  { Entity: 'Togo', Code: 'TGO', Year: 2015, Continent: 'Africa' },
  { Entity: 'Tokelau', Code: 'TKL', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Tonga', Code: 'TON', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Transnistria', Code: 'OWID_TRS', Year: 2015, Continent: 'Europe' },
  { Entity: 'Trinidad and Tobago', Code: 'TTO', Year: 2015, Continent: 'North America' },
  { Entity: 'Tunisia', Code: 'TUN', Year: 2015, Continent: 'Africa' },
  { Entity: 'Turkey', Code: 'TUR', Year: 2015, Continent: 'Asia' },
  { Entity: 'Turkmenistan', Code: 'TKM', Year: 2015, Continent: 'Asia' },
  {
    Entity: 'Turks and Caicos Islands',
    Code: 'TCA',
    Year: 2015,
    Continent: 'North America',
  },
  { Entity: 'Tuscany', Code: 'OWID_TUS', Year: 2015, Continent: 'Europe' },
  { Entity: 'Tuvalu', Code: 'TUV', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Two Sicilies', Code: 'OWID_SIC', Year: 2015, Continent: 'Europe' },
  { Entity: 'USSR', Code: 'OWID_USS', Year: 2015, Continent: 'Europe' },
  { Entity: 'Uganda', Code: 'UGA', Year: 2015, Continent: 'Africa' },
  { Entity: 'Ukraine', Code: 'UKR', Year: 2015, Continent: 'Europe' },
  { Entity: 'United Arab Emirates', Code: 'ARE', Year: 2015, Continent: 'Asia' },
  { Entity: 'United Kingdom', Code: 'GBR', Year: 2015, Continent: 'Europe' },
  { Entity: 'United Korea', Code: 'OWID_KRU', Year: 2015, Continent: 'Asia' },
  { Entity: 'United States', Code: 'USA', Year: 2015, Continent: 'North America' },
  {
    Entity: 'United States Minor Outlying Islands',
    Code: 'UMI',
    Year: 2015,
    Continent: 'Oceania',
  },
  {
    Entity: 'United States Virgin Islands',
    Code: 'VIR',
    Year: 2015,
    Continent: 'North America',
  },
  { Entity: 'Uruguay', Code: 'URY', Year: 2015, Continent: 'South America' },
  { Entity: 'Uzbekistan', Code: 'UZB', Year: 2015, Continent: 'Asia' },
  { Entity: 'Vanuatu', Code: 'VUT', Year: 2015, Continent: 'Oceania' },
  { Entity: 'Vatican', Code: 'VAT', Year: 2015, Continent: 'Europe' },
  { Entity: 'Venezuela', Code: 'VEN', Year: 2015, Continent: 'South America' },
  { Entity: 'Vietnam', Code: 'VNM', Year: 2015, Continent: 'Asia' },
  { Entity: 'Wallis and Futuna', Code: 'WLF', Year: 2015, Continent: 'Oceania' },
  { Entity: 'West Germany', Code: 'OWID_GFR', Year: 2015, Continent: 'Europe' },
  { Entity: 'Western Sahara', Code: 'ESH', Year: 2015, Continent: 'Africa' },
  { Entity: 'Wuerttemburg', Code: 'OWID_WRT', Year: 2015, Continent: 'Europe' },
  { Entity: 'Yemen', Code: 'YEM', Year: 2015, Continent: 'Asia' },
  { Entity: 'Yemen Arab Republic', Code: 'OWID_YAR', Year: 2015, Continent: 'Asia' },
  { Entity: "Yemen People's Republic", Code: 'OWID_YPR', Year: 2015, Continent: 'Asia' },
  { Entity: 'Yugoslavia', Code: 'OWID_YGS', Year: 2015, Continent: 'Europe' },
  { Entity: 'Zambia', Code: 'ZMB', Year: 2015, Continent: 'Africa' },
  { Entity: 'Zanzibar', Code: 'OWID_ZAN', Year: 2015, Continent: 'Africa' },
  { Entity: 'Zimbabwe', Code: 'ZWE', Year: 2015, Continent: 'Africa' },
  { Entity: 'Åland Islands', Code: 'ALA', Year: 2015, Continent: 'Europe' },
];
